//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tudong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_MUAGAME
    {
        public int idChiTIet { get; set; }
        public string idGame { get; set; }
        public string idMua { get; set; }
        public Nullable<int> discount { get; set; }
        public int gia { get; set; }
    
        public virtual GAME GAME { get; set; }
        public virtual MUAGAME MUAGAME { get; set; }
        public virtual GAME GAME1 { get; set; }
        public virtual MUAGAME MUAGAME1 { get; set; }
    }
}
