//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tudong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAME()
        {
            this.CHITIET_MUAGAME = new HashSet<CHITIET_MUAGAME>();
            this.CHITIET_MUAGAME1 = new HashSet<CHITIET_MUAGAME>();
        }
    
        public string idGame { get; set; }
        public string name { get; set; }
        public string moTa { get; set; }
        public int gia { get; set; }
        public Nullable<int> idNPH { get; set; }
        public string idTheLoai { get; set; }
        public string image_url { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<int> giamGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_MUAGAME> CHITIET_MUAGAME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_MUAGAME> CHITIET_MUAGAME1 { get; set; }
        public virtual USER USER { get; set; }
        public virtual THELOAI THELOAI { get; set; }
        public virtual THELOAI THELOAI1 { get; set; }
    }
}
