//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tudong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUAGAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUAGAME()
        {
            this.CHITIET_MUAGAME = new HashSet<CHITIET_MUAGAME>();
            this.CHITIET_MUAGAME1 = new HashSet<CHITIET_MUAGAME>();
        }
    
        public string idMua { get; set; }
        public Nullable<int> idND { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string trangThai { get; set; }
        public Nullable<System.DateTime> ngayMua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_MUAGAME> CHITIET_MUAGAME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_MUAGAME> CHITIET_MUAGAME1 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public MUAGAME(string idMua, int? idND, bool? Deleted, string trangThai, DateTime? ngayMua) : this()
        {
            this.idMua = idMua;
            this.idND = idND;
            this.Deleted = Deleted;
            this.trangThai = trangThai;
            this.ngayMua = ngayMua;
        }
    }
}
